name: CI for local local-action
on:
  push:
    branches-ignore:
      - main

jobs:
  run-tests:
    if: github.repository == 'githubtraining/exercise-reference-a-codeql-query'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/codeql/codeql-config.yml
        - uses: actions/setup-node@v3
          with:
          node-version: '16'
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: npm ci

      - name: run tests
        run: npm run test

        
